### PR TITLE
support reading through list of rotated logs

### PR DESCRIPTION
**Pull request by mosheeshel**
Following my previous PR #5 - continuing work on support for GC log rotation.

Script will now find correct file GC is writing to at JTune start time,  and on exit will now read all additional GC log files created while script was running (if JVM rotated during process run). 

Changed flow to depend on file last modified date (previously it assumed the increment number is the way to go).

Still a possible issue, since script reads the log files only at the end of the collection that GC will have rotated more than once through the rotation size, and so we will lose some of the GC Logs, this is a somewhat remote option, and resolving it would change the script flow, so I'll leave it for now.

### CODE REVIEW

**Comment by mosheeshel** [comment]
@ericbullen , any comments?

**Comment by ericbullen** [comment]
Hi mosheeshel. Thanks for the pull request. It's going to take me a bit of time to review your changes (lots going on at work). I never implemented this feature b/c I couldn't think of a clean/non-hacky way to do it. Yours looks good, but I'm going to have to test all the corner cases. Don't let me forget to follow-up. :-)

**Comment by mosheeshel** [comment]
Hey @ericbullen , believe me I understand work things, this PR should have been pushed over a month ago, but was pushed back due to workload issues :smile: 
take your time to review and test (and might I suggest adding those tests to the repo so contributors can run them to verify their solutions work - I realize testing this is not trivial, but, well...).
No pressure, and I'll keep on reminding every week or two. this is a great project that we have started using and are getting some nice value from.

**Comment by mosheeshel** [comment]
Hi @ericbullen  a friendly reminder :smile:

**Comment by mosheeshel** [comment]
@ericbullen still waiting

**Comment by mosheeshel** [comment]
@ericbullen gonna stop bugging and wait for you to get to it when you can.

**Comment by mosheeshel** [comment]
@ericbullen any news? is this project abandoned?

**Comment by mosheeshel** [comment]
@ericbullen another reminder, is it even relevant to rebase here?

**Pull request closed without merging**
